name: repo
description: Interface to create repositories
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  provider: ^6.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
