name: repo_scaffold
description: Interface to create repositories
version: 1.0.1
homepage: https://github.com/andreaswierm/repo

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  provider: ">=6.0.1 <7.0.0"

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
